// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EbayAutomationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302215336_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EbayCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.Property<string>("EbayCategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ebay_category_name");

                    b.PrimitiveCollection<List<string>>("Keyword")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("DirtySku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EbayCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("EbayCategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("dirtySkus", (string)null);
                });

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableInventory")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SkuId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SkuId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EbayItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ebay_item_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<int>("SkuEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EbayItemId")
                        .IsUnique();

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("SkuEntityId");

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Ebay_Category_Id")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.PrimitiveCollection<string[]>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("ItemSpecifics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("item_specifics");

                    b.Property<string>("OfferId")
                        .HasColumnType("text")
                        .HasColumnName("offer_id");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sell_price");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("SkuStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("sku_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("availableInventory")
                        .HasColumnType("integer")
                        .HasColumnName("available_inventory");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SkuCode")
                        .IsUnique();

                    b.HasIndex("SkuStatus");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("DirtySku", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("DirtySkus")
                        .HasForeignKey("EbayCategoryId")
                        .HasPrincipalKey("EbayCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.HasOne("Sku", "sku")
                        .WithMany()
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sku");
                });

            modelBuilder.Entity("Listing", b =>
                {
                    b.HasOne("Sku", "SkuEntity")
                        .WithMany()
                        .HasForeignKey("SkuEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkuEntity");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("DirtySkus");
                });
#pragma warning restore 612, 618
        }
    }
}
