// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EbayAutomationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260221035741_AddOfferIdAndTrackingColumns")]
    partial class AddOfferIdAndTrackingColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EbayCategoryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ebay_category_id");

                    b.Property<string>("EbayCategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ebay_category_name");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("keyword");

                    b.HasKey("Id");

                    b.HasIndex("EbayCategoryId")
                        .IsUnique();

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("DirtySku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("dirtySkus", (string)null);
                });

            modelBuilder.Entity("Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EbayItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ebay_item_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("EbayItemId")
                        .IsUnique();

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.PrimitiveCollection<string[]>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("ItemSpecifics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("item_specifics");

                    b.Property<string>("Pid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pid");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sell_price");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("SkuStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("sku_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("offerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("offer_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SkuCode")
                        .IsUnique();

                    b.HasIndex("SkuStatus");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("DirtySku", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("DirtySkus")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Listing", b =>
                {
                    b.HasOne("Sku", "SkuEntity")
                        .WithOne("Listing")
                        .HasForeignKey("Listing", "Sku")
                        .HasPrincipalKey("Sku", "SkuCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkuEntity");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("DirtySkus");
                });

            modelBuilder.Entity("Sku", b =>
                {
                    b.Navigation("Listing");
                });
#pragma warning restore 612, 618
        }
    }
}
