// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EbayAutomationService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308002118_LineItemAndEbayOrderTable")]
    partial class LineItemAndEbayOrderTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EbayCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.Property<string>("EbayCategoryName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ebay_category_name");

                    b.Property<bool>("IsPopulated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_populated");

                    b.PrimitiveCollection<List<string>>("Keyword")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("DirtySku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EbayCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.HasIndex("EbayCategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("dirtySkus", (string)null);
                });

            modelBuilder.Entity("EbayOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line1");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address_line2");

                    b.Property<string>("BuyerFullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("buyer_full_name");

                    b.Property<string>("BuyerUsername")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("buyer_username");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EbayOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ebay_order_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("OrderFulfillmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_fulfillment_status");

                    b.Property<string>("OrderPaymentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_payment_status");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EbayOrderId")
                        .IsUnique();

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableInventory")
                        .HasColumnType("integer")
                        .HasColumnName("AvailableInventory");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("SkuId")
                        .HasColumnType("integer")
                        .HasColumnName("SkuId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SkuId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("InventoryItems", (string)null);
                });

            modelBuilder.Entity("LineItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CjOrderId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cj_order_id");

                    b.Property<string>("LineItemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_item_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tracking_number");

                    b.HasKey("Id");

                    b.HasIndex("LineItemId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Listing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<string>("listingId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ListingId");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("listingId")
                        .IsUnique();

                    b.ToTable("listings", (string)null);
                });

            modelBuilder.Entity("OfferItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Ebay_Category_Id")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.Property<int>("InventoryId")
                        .HasColumnType("integer")
                        .HasColumnName("InventoryId");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OfferId");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("Quantity");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("SellPrice");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("InventoryId")
                        .IsUnique();

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Offers", (string)null);
                });

            modelBuilder.Entity("Sku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("Ebay_Category_Id")
                        .HasColumnType("integer")
                        .HasColumnName("ebay_category_id");

                    b.PrimitiveCollection<string[]>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("image_urls");

                    b.Property<string>("ItemSpecifics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("item_specifics");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sell_price");

                    b.Property<string>("SkuCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<string>("SkuStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("sku_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("availableInventory")
                        .HasColumnType("integer")
                        .HasColumnName("available_inventory");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SkuCode")
                        .IsUnique();

                    b.HasIndex("SkuStatus");

                    b.ToTable("skus", (string)null);
                });

            modelBuilder.Entity("DirtySku", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("DirtySkus")
                        .HasForeignKey("EbayCategoryId")
                        .HasPrincipalKey("EbayCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InventoryItem", b =>
                {
                    b.HasOne("Sku", "sku")
                        .WithOne()
                        .HasForeignKey("InventoryItem", "SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sku");
                });

            modelBuilder.Entity("LineItem", b =>
                {
                    b.HasOne("EbayOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Listing", b =>
                {
                    b.HasOne("OfferItem", "Offer")
                        .WithOne()
                        .HasForeignKey("Listing", "OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("OfferItem", b =>
                {
                    b.HasOne("InventoryItem", "Inventory")
                        .WithOne()
                        .HasForeignKey("OfferItem", "InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("DirtySkus");
                });

            modelBuilder.Entity("EbayOrder", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
